spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3316/blog_system?useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000 # 20秒
      minimum-idle: 5 # 最小连接数
      maximum-pool-size: 12 # 最大连接数
      idle-timeout: 300000 # 5分钟
      max-lifetime: 1200000 # 20分钟
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        connection.provider_disables_autocommit: false
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080

jwt:
  secret: myStrongSecretKey123!@#ForJwtSecurityImplementation
  expiration: 86400000 # 24小时 

mvc:
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600 

jackson:
  serialization:
    fail-on-empty-beans: false 

openai:
  api:
    key: ${OPENAI_API_KEY:hk-433b5g1000034436f01f7a8e467af1c7bb77d74d4672f2ad}
    url: ${OPENAI_API_URL:https://api.openai-hk.com/v1/chat/completions}